server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:game;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: capia
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      default_batch_fetch_size: 100
      hibernate:
        jdbc:
          batch_size: 50
  flyway:
    enabled: true
logging:
  level:
    '[com.game.capia]': INFO # DEBUG 레벨부터 에러 확인할 수 있게 설정하기

file:
  path: ./upload/ # UPLOAD 폴더 상대경로 / AWS에 S3 사용하는게 좋음
